[package]
name = "event_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
rdev = "0.5.3"        # For capturing mouse and keyboard events
csv = "1.3.1"         # For writing to CSV files
eframe = "0.14.0"     # For building the desktop UI with egui
